### ISSUE TITLE
Draw on top of another application?

### ISSUE THREAD

**Issue by idkRage** [Daninet/node-gdi#1]
Title ^

**Comment by SalameDefumado** [comment]
That would be really useful +1

**Comment by Daninet** [comment]
Thank you for the interest in this library, I will consider your request.
But in order to understand it better, could you provide me more details about this use case? Do you only need a transparent background for the window or maybe something more?

**Comment by SalameDefumado** [comment]
@Daninet would be cool if we had the option to set: transparent background, always on top, and click-trough.

**Comment by Daninet** [comment]
I've added always on top and transparent background support in version 0.3.1. Transparent regions have click-through.

**Comment by Daninet** [comment]
There is an example for using these functionalities here: https://github.com/Daninet/node-gdi/blob/master/examples/08-transparent.js
